/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee Li
 */
public class Historyofanyang2 extends javax.swing.JFrame {

    
    public Historyofanyang2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblHistory1 = new javax.swing.JLabel();
        lblHistory2 = new javax.swing.JLabel();
        lblHistory5 = new javax.swing.JLabel();
        lblHistory6 = new javax.swing.JLabel();
        lblHistory7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnGotofirstpage = new javax.swing.JButton();
        btnBackonepage = new javax.swing.JButton();
        lblPicture1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHistory1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory1.setText("On the eve of the founding of the People's Republic of China");

        lblHistory2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory2.setText("August 1, the establishment of plain province, Anyang for provincial municipality. November 30, 1952,");

        lblHistory5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory5.setText("In 1983, the State Council decided to classify Anyang County, Marin, Jun County, ");

        lblHistory6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory6.setText(" In February 1986, the administrative division of Henan province was adjusted to classify Qi County and Jun County into Hebi, ");

        lblHistory7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory7.setText("Tangyin County and Qi County as Anyang, and to implement the county system with the city.");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("and the Neihuang County and Hua County of the genus Puyang were classified as Anyang.");

        btnNext.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnNext.setForeground(new java.awt.Color(153, 153, 255));
        btnNext.setText("Next Page moving to the Mapping part");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnGotofirstpage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnGotofirstpage.setForeground(new java.awt.Color(0, 204, 51));
        btnGotofirstpage.setText("Go back to the first Page");
        btnGotofirstpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGotofirstpageActionPerformed(evt);
            }
        });

        btnBackonepage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnBackonepage.setForeground(new java.awt.Color(255, 204, 0));
        btnBackonepage.setText("Go back for one page");
        btnBackonepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackonepageActionPerformed(evt);
            }
        });

        lblPicture1.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\th.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblHistory2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addGap(315, 315, 315))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnGotofirstpage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBackonepage, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHistory5)
                                        .addComponent(lblHistory7)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblHistory6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)))
                .addComponent(lblPicture1)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHistory2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHistory5)
                        .addGap(18, 18, 18)
                        .addComponent(lblHistory7)
                        .addGap(18, 18, 18)
                        .addComponent(lblHistory6)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGotofirstpage)
                    .addComponent(btnBackonepage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.setVisible(false);
       
        new TheMappingofanyang().setVisible(true);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnGotofirstpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGotofirstpageActionPerformed
        this.setVisible(false);
       
        new cultureofmyhometown().setVisible(true);
    }//GEN-LAST:event_btnGotofirstpageActionPerformed

    private void btnBackonepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackonepageActionPerformed
        this.setVisible(false);
       
        new TheHistoryofanyang().setVisible(true);
    }//GEN-LAST:event_btnBackonepageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historyofanyang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historyofanyang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historyofanyang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historyofanyang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historyofanyang2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackonepage;
    private javax.swing.JButton btnGotofirstpage;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHistory1;
    private javax.swing.JLabel lblHistory2;
    private javax.swing.JLabel lblHistory5;
    private javax.swing.JLabel lblHistory6;
    private javax.swing.JLabel lblHistory7;
    private javax.swing.JLabel lblPicture1;
    // End of variables declaration//GEN-END:variables
}
