/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee Li
 */
public class TheEatingofanyang extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public TheEatingofanyang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEating1 = new javax.swing.JLabel();
        lblPicture1 = new javax.swing.JLabel();
        lblEating2 = new javax.swing.JLabel();
        lblEating4 = new javax.swing.JLabel();
        lblEating5 = new javax.swing.JLabel();
        lblEating6 = new javax.swing.JLabel();
        lblEating7 = new javax.swing.JLabel();
        lblEating8 = new javax.swing.JLabel();
        lblEating9 = new javax.swing.JLabel();
        btnGotonextpage = new javax.swing.JButton();
        btnGobackonepage = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEating1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lblEating1.setForeground(new java.awt.Color(204, 153, 0));
        lblEating1.setText("Eating in Anyang");

        lblPicture1.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\QQ图片20190127142341.jpg")); // NOI18N

        lblEating2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating2.setText("Flat powder dish is a traditional famous dish in Anyang area of Henan province, belonging to the cuisine of Yu cuisine.");

        lblEating4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating4.setText("It is one of the favorite meals for Anyang residents.");

        lblEating5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating5.setText("Flat powder dishes to the main material of powder, with greens, tofu, pig blood, etc., in a large iron pot to cook. ");

        lblEating6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating6.setText("The key to flat powder is the soup, the taste of the soup is good or bad, directly affect the taste of flat powder dishes,");

        lblEating7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating7.setText("Therefore, Anyang flat powder vegetable operators have been working on the practice of soup, so that the taste of flat powder is constantly improving.");

        lblEating8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblEating8.setText("The essence of eating flat powder vegetables is chili peppers, chili peppers should be fragrant and slightly spicy.");

        lblEating9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblEating9.setForeground(new java.awt.Color(255, 51, 51));
        lblEating9.setText("(It is ok to put some sugar in it :)");

        btnGotonextpage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnGotonextpage.setText("Go to next page");
        btnGotonextpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGotonextpageActionPerformed(evt);
            }
        });

        btnGobackonepage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnGobackonepage.setForeground(new java.awt.Color(255, 204, 0));
        btnGobackonepage.setText("Go back one page");
        btnGobackonepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGobackonepageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEating2)
                    .addComponent(lblEating4, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEating5)
                    .addComponent(lblEating6)
                    .addComponent(lblEating7)
                    .addComponent(lblEating8, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblEating9, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblPicture1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGotonextpage)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnGobackonepage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(lblEating1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEating1)
                        .addGap(42, 42, 42)
                        .addComponent(lblPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnGotonextpage)
                        .addGap(90, 90, 90)
                        .addComponent(btnGobackonepage)))
                .addGap(41, 41, 41)
                .addComponent(lblEating2)
                .addGap(18, 18, 18)
                .addComponent(lblEating4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEating5)
                .addGap(20, 20, 20)
                .addComponent(lblEating6)
                .addGap(18, 18, 18)
                .addComponent(lblEating7)
                .addGap(18, 18, 18)
                .addComponent(lblEating8)
                .addGap(18, 18, 18)
                .addComponent(lblEating9)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGobackonepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGobackonepageActionPerformed
        this.setVisible(false);
       
        new TheMappingofanyang().setVisible(true); 
        
    }//GEN-LAST:event_btnGobackonepageActionPerformed

    private void btnGotonextpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGotonextpageActionPerformed
        this.setVisible(false);
       
        new EatingNum2().setVisible(true);
    }//GEN-LAST:event_btnGotonextpageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheEatingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheEatingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheEatingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheEatingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheEatingofanyang().setVisible(true);
            }
        });
    }

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGobackonepage;
    private javax.swing.JButton btnGotonextpage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEating1;
    private javax.swing.JLabel lblEating2;
    private javax.swing.JLabel lblEating4;
    private javax.swing.JLabel lblEating5;
    private javax.swing.JLabel lblEating6;
    private javax.swing.JLabel lblEating7;
    private javax.swing.JLabel lblEating8;
    private javax.swing.JLabel lblEating9;
    private javax.swing.JLabel lblPicture1;
    // End of variables declaration//GEN-END:variables
}
