/*
 * 
 */

/**
 *
 * @author Lee Li
 */
public class TheHistoryofanyang extends javax.swing.JFrame {

    /**
     * Creates new form NewjFrame2
     */
    public TheHistoryofanyang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblHistory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHistory2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHistory3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHistory4 = new javax.swing.JLabel();
        lblHistory5 = new javax.swing.JLabel();
        lblHistory6 = new javax.swing.JLabel();
        lblHistory7 = new javax.swing.JLabel();
        lblHistory8 = new javax.swing.JLabel();
        lblHistory9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("History of Anyang");

        lblHistory.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory.setText("Anyang is one of the six ancient capitals of the national historical and cultural city and China.");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\QQ图片20190127142405.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        lblHistory2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory2.setText("Xia Dynasty's sixth monarch, Ni, moved the capital from Chui (now Kaifeng Village) to Xihe (now Anyang Tangyin Xihe) for about 35 years.");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\QQ图片20190127142354.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        lblHistory3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory3.setText("Shang Dynasty 12th Monarch River Such, from the hustle and bustle (now Anyang East) 9 years.");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\QQ图片20190127142413.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        lblHistory4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory4.setText("The 20th monarch of the Shang Dynasty, the 14th year of the reign.");

        lblHistory5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory5.setText("Self-ml (now Shangqiu, Henan) moved to North Mongolia (now Anyang District), the \"North Monk\" renamed \"Yin.\"");

        lblHistory6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory6.setText("In the 15th year of his reign, he built Yin Yi. The Shang Dynasty was built in the middle and late 282 years.");

        lblHistory7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory7.setText("The Yin Hui in Anyang is the first capital site in China to be tested so far in literature and confirmed by archaeology and Oracle.");

        lblHistory8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory8.setText("Anyang is the land of Oracle Discovery, the birthplace of Zhouyi, Yin Hui and the Chinese Grand Canal Weihe (Yongji Canal),");

        lblHistory9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblHistory9.setText("Sliding County Section Two World Cultural heritage sites. ");

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 102));
        jButton1.setText("Next Page ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jButton2.setText("Go back one page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblHistory3, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(lblHistory4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHistory2, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblHistory6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHistory7)
                            .addComponent(lblHistory5, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblHistory8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lblHistory9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(jButton1)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 665, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 663, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(lblHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblHistory2)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(lblHistory3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(lblHistory4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistory5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistory6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistory7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblHistory8)
                .addGap(18, 18, 18)
                .addComponent(lblHistory9)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1208, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1208, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.setVisible(false);
       
        new Historyofanyang2().setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
       
        new cultureofmyhometown().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheHistoryofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheHistoryofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheHistoryofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheHistoryofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TheHistoryofanyang().setVisible(true);
        });
    }

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHistory2;
    private javax.swing.JLabel lblHistory3;
    private javax.swing.JLabel lblHistory4;
    private javax.swing.JLabel lblHistory5;
    private javax.swing.JLabel lblHistory6;
    private javax.swing.JLabel lblHistory7;
    private javax.swing.JLabel lblHistory8;
    private javax.swing.JLabel lblHistory9;
    // End of variables declaration//GEN-END:variables
}
