/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee Li
 */
public class TheMappingofanyang extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public TheMappingofanyang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMapping = new javax.swing.JLabel();
        lblMapping1 = new javax.swing.JLabel();
        lblMapping2 = new javax.swing.JLabel();
        lblMapping3 = new javax.swing.JLabel();
        lblMapping4 = new javax.swing.JLabel();
        lblMapping5 = new javax.swing.JLabel();
        lblMapping6 = new javax.swing.JLabel();
        lblMapping7 = new javax.swing.JLabel();
        Picture1 = new javax.swing.JLabel();
        Picture2 = new javax.swing.JLabel();
        btnGobackonepage = new javax.swing.JButton();
        btnNextpage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMapping.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lblMapping.setForeground(new java.awt.Color(255, 102, 102));
        lblMapping.setText("Mapping of Anyang");

        lblMapping1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping1.setText("Anyang is located in the northernmost part of Henan province");

        lblMapping2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping2.setText("and is located at the junction of Shanxi, Hebei and Henan provinces.");

        lblMapping3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping3.setText("Leaning on the towering and steep Taihang mountains, the east of the vast expanse of the North China Plain.");

        lblMapping4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping4.setText("Geographical coordinates between 113°37′ from east longitude to 114°58′,");

        lblMapping5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping5.setText(" north latitude 35°12′ to 36°22′, located in the junction of Jin, Hebei and Yu provinces,");

        lblMapping6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping6.setText("West of the Taihang Mountains and Shanxi province Changzhi, north and Hebei province Hanhan connected, east and Puyang adjacent,");

        lblMapping7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblMapping7.setText("South and Hebi, Xinxiang connected, the total area of the city is 5599 square kilometers. ");

        Picture1.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\th1MUJTK8I.jpg")); // NOI18N

        Picture2.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\thI3FBDVZ5.jpg")); // NOI18N

        btnGobackonepage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnGobackonepage.setText("Go back one page");
        btnGobackonepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGobackonepageActionPerformed(evt);
            }
        });

        btnNextpage.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        btnNextpage.setForeground(new java.awt.Color(0, 255, 255));
        btnNextpage.setText("Go to next page");
        btnNextpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextpageActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setText("Go to the first page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMapping6)
                                    .addComponent(lblMapping5)
                                    .addComponent(lblMapping7))
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnGobackonepage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNextpage)
                                .addGap(87, 87, 87)
                                .addComponent(jButton1)
                                .addGap(48, 48, 48)))
                        .addComponent(Picture2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMapping4)
                            .addComponent(lblMapping3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(lblMapping, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMapping2)
                            .addComponent(lblMapping1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Picture1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMapping)
                        .addGap(31, 31, 31)
                        .addComponent(lblMapping1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMapping2)
                        .addGap(20, 20, 20)
                        .addComponent(lblMapping3)
                        .addGap(21, 21, 21)
                        .addComponent(lblMapping4))
                    .addComponent(Picture1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMapping5)
                        .addGap(18, 18, 18)
                        .addComponent(lblMapping6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMapping7)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGobackonepage)
                            .addComponent(btnNextpage)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Picture2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGobackonepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGobackonepageActionPerformed
        this.setVisible(false);
       
        new Historyofanyang2().setVisible(true);
        
    }//GEN-LAST:event_btnGobackonepageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false);
       
        new cultureofmyhometown().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNextpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextpageActionPerformed
         this.setVisible(false);
       
        new TheEatingofanyang().setVisible(true);
    }//GEN-LAST:event_btnNextpageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheMappingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheMappingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheMappingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheMappingofanyang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheMappingofanyang().setVisible(true);
            }
        });
    }

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Picture1;
    private javax.swing.JLabel Picture2;
    private javax.swing.JButton btnGobackonepage;
    private javax.swing.JButton btnNextpage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMapping;
    private javax.swing.JLabel lblMapping1;
    private javax.swing.JLabel lblMapping2;
    private javax.swing.JLabel lblMapping3;
    private javax.swing.JLabel lblMapping4;
    private javax.swing.JLabel lblMapping5;
    private javax.swing.JLabel lblMapping6;
    private javax.swing.JLabel lblMapping7;
    // End of variables declaration//GEN-END:variables
}
